import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { NgForm } from '@angular/forms';
import { Observable, Subscription } from 'rxjs';

import { HeroeModel } from '../../models/heroe.model';
import { HeroesService } from '../../services/heroes.service';
import { TranslationService } from '../../services/translation.service';

import Swal from 'sweetalert2';

@Component({
  selector: 'app-heroe',
  templateUrl: './heroe.component.html'
})
export class HeroeComponent implements OnInit, OnDestroy {

  heroe: HeroeModel = new HeroeModel();
  
  // Propiedades traducibles
  heroeTitle: string = '';
  heroeSubtitle: string = '';
  heroeBack: string = '';
  heroeFirebaseId: string = '';
  heroeAutoGenerated: string = '';
  heroeName: string = '';
  heroeNamePlaceholder: string = '';
  heroePower: string = '';
  heroePowerPlaceholder: string = '';
  heroeState: string = '';
  statusAlive: string = '';
  statusDead: string = '';
  heroeSave: string = '';
  
  private langSubscription: Subscription;

  constructor( 
    private heroesService: HeroesService,
    private route: ActivatedRoute,
    public translationService: TranslationService
  ) { 
    console.log('[HeroeComponent] Constructor');
  }

  ngOnInit() {
    console.log('[HeroeComponent] ngOnInit');
    
    // Actualizar textos inmediatamente
    this.updateTexts();

    // Obtengo el id de la ruta
    const id = this.route.snapshot.paramMap.get('id');

    if ( id !== 'nuevo' ) {
      // Recupero de FireBase toda la información del héroe
      this.heroesService.getHeroe( id )
        .subscribe( (resp: HeroeModel) => {
          this.heroe = resp;
          this.heroe.id = id;
        });
    }
    
    // Escuchar cambios de idioma
    this.langSubscription = this.translationService.currentLanguage$.subscribe((lang) => {
      console.log('[HeroeComponent] Detectado cambio de idioma a:', lang);
      this.updateTexts();
    });
  }
  
  ngOnDestroy() {
    if (this.langSubscription) {
      this.langSubscription.unsubscribe();
    }
  }
  
  private updateTexts(): void {
    console.log('[HeroeComponent] updateTexts()');
    this.heroeTitle = this.translationService.translate('heroe.title');
    this.heroeSubtitle = this.translationService.translate('heroe.subtitle');
    this.heroeBack = this.translationService.translate('heroe.back');
    this.heroeFirebaseId = this.translationService.translate('heroe.firebaseId');
    this.heroeAutoGenerated = this.translationService.translate('heroe.autoGenerated');
    this.heroeName = this.translationService.translate('heroe.name');
    this.heroeNamePlaceholder = this.translationService.translate('heroe.namePlaceholder');
    this.heroePower = this.translationService.translate('heroe.power');
    this.heroePowerPlaceholder = this.translationService.translate('heroe.powerPlaceholder');
    this.heroeState = this.translationService.translate('heroe.state');
    this.statusAlive = this.translationService.translate('status.alive');
    this.statusDead = this.translationService.translate('status.dead');
    this.heroeSave = this.translationService.translate('heroe.save');
    
    console.log('[HeroeComponent] Titulo actualizado:', this.heroeTitle);
  }

  t(key: string): string {
    return this.translationService.translate(key);
  }

  guardar( form: NgForm ) {

    if ( form.invalid ) {
      console.log('Formulario no válido');
      return;
    }

    Swal.fire({
      title: this.t('alert.wait'),
      text: this.t('alert.saving'),
      icon: 'info',
      allowOutsideClick: false
    });
    Swal.showLoading();

    let peticion: Observable<any>;

    if ( this.heroe.id ) {
      peticion = this.heroesService.actualizarHeroe( this.heroe );
    } else {
      peticion = this.heroesService.crearHeroe( this.heroe );
    }

    peticion.subscribe( resp => {
      Swal.fire({
        title: this.heroe.nombre,
        text: this.t('alert.updated'),
        icon: 'success'
      });
    });
  }
}