import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';

export type Language = 'es' | 'eu';

export interface Translations {
  [key: string]: {
    es: string;
    eu: string;
  };
}

@Injectable({
  providedIn: 'root'
})
export class TranslationService {
  private readonly STORAGE_KEY = 'heroes_language';
  private currentLanguageSubject: BehaviorSubject<Language>;
  public currentLanguage$: Observable<Language>;

  private translations: Translations = {
    'heroes.title': {
      es: 'Listado de Heroes',
      eu: 'Heroien Zerrenda'
    },
    'heroes.add': {
      es: 'Agregar',
      eu: 'Gehitu'
    },
    'heroes.noRecords': {
      es: 'No hay registros',
      eu: 'Ez dago erregistrorik'
    },
    'heroes.loading': {
      es: 'Cargando',
      eu: 'Kargatzen'
    },
    'heroes.wait': {
      es: 'Espere por favor',
      eu: 'Itxaron mesedez'
    },
    'table.number': {
      es: '#',
      eu: '#'
    },
    'table.name': {
      es: 'Nombre',
      eu: 'Izena'
    },
    'table.power': {
      es: 'Poder',
      eu: 'Boterea'
    },
    'table.status': {
      es: 'Vivo',
      eu: 'Bizirik'
    },
    'table.tools': {
      es: 'Tools',
      eu: 'Tresnak'
    },
    'status.alive': {
      es: 'Vivo',
      eu: 'Bizirik'
    },
    'status.dead': {
      es: 'Muerto',
      eu: 'Hilda'
    },
    'heroe.title': {
      es: 'Heroe',
      eu: 'Heroia'
    },
    'heroe.subtitle': {
      es: 'Nombre del Heroe',
      eu: 'Heroiaren Izena'
    },
    'heroe.back': {
      es: 'Regresar',
      eu: 'Itzuli'
    },
    'heroe.firebaseId': {
      es: 'Firebase ID',
      eu: 'Firebase ID'
    },
    'heroe.autoGenerated': {
      es: 'Este campo es autogenerado',
      eu: 'Eremu hau automatikoki sortzen da'
    },
    'heroe.name': {
      es: 'Nombre',
      eu: 'Izena'
    },
    'heroe.namePlaceholder': {
      es: 'Nombre del heroe',
      eu: 'Heroiaren izena'
    },
    'heroe.power': {
      es: 'Poder',
      eu: 'Boterea'
    },
    'heroe.powerPlaceholder': {
      es: 'Poder del heroe',
      eu: 'Heroiaren boterea'
    },
    'heroe.state': {
      es: 'Estado',
      eu: 'Egoera'
    },
    'heroe.save': {
      es: 'Guardar',
      eu: 'Gorde'
    },
    'alert.wait': {
      es: 'Espere',
      eu: 'Itxaron'
    },
    'alert.saving': {
      es: 'Guardando informacion',
      eu: 'Informazioa gordetzen'
    },
    'alert.updated': {
      es: 'Se ha actualizado correctamente',
      eu: 'Ondo eguneratu da'
    },
    'alert.confirmDelete': {
      es: 'Borrado de Heroe',
      eu: 'Heroiaren ezabaketa'
    },
    'alert.confirmDeleteMessage': {
      es: 'Estas seguro de borrar',
      eu: 'Ziur zaude ezabatu egingo duzula'
    },
    'language.spanish': {
      es: 'Espanol',
      eu: 'Gaztelania'
    },
    'language.basque': {
      es: 'Euskera',
      eu: 'Euskara'
    }
  };

  constructor() {
    const savedLang = this.getSavedLanguage();
    this.currentLanguageSubject = new BehaviorSubject<Language>(savedLang);
    this.currentLanguage$ = this.currentLanguageSubject.asObservable();
  }

  private getSavedLanguage(): Language {
    const saved = localStorage.getItem(this.STORAGE_KEY);
    return (saved === 'eu') ? 'eu' : 'es';
  }

  setLanguage(lang: Language): void {
    localStorage.setItem(this.STORAGE_KEY, lang);
    this.currentLanguageSubject.next(lang);
  }

  getCurrentLanguage(): Language {
    return this.currentLanguageSubject.value;
  }

  translate(key: string): string {
    const currentLang = this.getCurrentLanguage();
    const translation = this.translations[key];
    
    if (!translation) {
      console.warn(`Translation missing for key: ${key}`);
      return key;
    }
    
    return translation[currentLang] || translation.es || key;
  }
}